DEPS = \
       	Makefile \
        *.h \

OBJS = \
	Box.o \
	Color.o \
	Config.o \
	Entity.o \
	Hash.o \
	List.o \
	NodeIO.o \
	Misc.o \
	Rectangle.o \
	Sys_glut.o \
	World.o \

LIBS = \

PROGS = \
	_test_node.exe \

include ../make/common.mk
