DEPS = \
       Makefile \
       common.mk \
       Arrow.h \
       Box.h \
       Color.h \
       Config.h \
       Entity.h \
       Hash.h \
       List.h \
       Misc.h \
       Node.h \
       Rectangle.h \
       Sys.h \
       World.h \

OBJS = Arrow.o \
       Box.o \
       Color.o \
       Config.o \
       Entity.o \
       Hash.o \
       List.o \
       NodeIO.o \
       Misc.o \
       Rectangle.o \
       Sys_glut.o \
       World.o \

include common.mk
