DEPS = \
       Makefile \
       ../make/common.mk \
       ../base/*.h \
       *.h

OBJS = \
       ConfigViz.o \
       Viz.o \

LIBS = \
       ../base/[A-Z]*.o \

PROGS = \
       vizmain.exe \

include ../make/common.mk
