DEPS = \
       Makefile \
       ../base/common.mk \
       ../base/*.h \
       *.h

OBJS = \
       main.o \
       ConfigViz.o \
       Viz.o \

LIBS = \
       ../base/*.o \

PROG = \
       main.exe \

include ../base/common.mk
